services:
  wisp-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
    env_file:
      - .env
